[package]
name = "factory-legacy-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.factory-legacy]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
