// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    farm_staking_proxy_v13
    (
        init => init
        upgrade => upgrade
        unstakeFarmTokens => unstake_farm_tokens
        setTransferRoleDualYieldToken => set_transfer_role_dual_yield_token
        getDualYieldTokenId => dual_yield_token_id
        getLpFarmAddress => lp_farm_address
        getStakingFarmAddress => staking_farm_address
        getPairAddress => pair_address
        getStakingTokenId => staking_token_id
        getFarmTokenId => staking_farm_token_id
        getLpFarmTokenId => lp_farm_token_id
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
