[package]
name = "router-abi"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[dependencies.router]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = ""1.0.1""
default-features = false
