// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            1
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    energy_update
    (
        init => init
        upgrade => upgrade
        updateFarmsEnergyForUser => update_farms_energy_for_user
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
