// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    simple_lock_legacy
    (
        init => init
        upgrade => upgrade
        unlockTokens => unlock_tokens_endpoint
        getLockedTokenId => locked_token
        removeLiquidityLockedToken => remove_liquidity_locked_token
        getLpProxyTokenId => lp_proxy_token
        exitFarmLockedToken => exit_farm_locked_token
        farmClaimRewardsLockedToken => farm_claim_rewards_locked_token
        getFarmProxyTokenId => farm_proxy_token
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
