[package]
name = "simple-lock-legacy-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dependencies.simple-lock-legacy]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
