[package]
name = "weekly-rewards-splitting"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = ""1.0.1""
features = ["esdt-token-payment-legacy-decode"]

[dependencies.energy-query]
path = "../energy-query"

[dependencies.week-timekeeping]
path = "../week-timekeeping"

[dependencies.common-types]
path = "../../common-types"

[dependencies.unwrappable]
path = "../../../common/traits/unwrappable"

[dependencies.math]
path = "../../../common/modules/math"
