[package]
name = "farm-staking-proxy-v13-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dependencies.farm-staking-proxy-v13]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
