[package]
name = "pause-all-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dev-dependencies]

[dependencies.pause-all]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
