[package]
name = "farm-v13"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "1.0.1"

[dev-dependencies]
num-bigint = "0.4"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.1"
