// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::external_view_init! {}

dharitri_sc_wasm_adapter::external_view_endpoints! {
    pair
    (
        getLpTokensSafePriceByDefaultOffset => get_lp_tokens_safe_price_by_default_offset
        getLpTokensSafePriceByRoundOffset => get_lp_tokens_safe_price_by_round_offset
        getLpTokensSafePriceByTimestampOffset => get_lp_tokens_safe_price_by_timestamp_offset
        getLpTokensSafePrice => get_lp_tokens_safe_price
        getSafePriceByDefaultOffset => get_safe_price_by_default_offset
        getSafePriceByRoundOffset => get_safe_price_by_round_offset
        getSafePriceByTimestampOffset => get_safe_price_by_timestamp_offset
        getSafePrice => get_safe_price
        getPriceObservation => get_price_observation_view
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
