[package]
name = "farm-v13-locked-rewards-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-v13-locked-rewards]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
